story_creation_task:
  description: >
    Create a comic story script for {topic} with:
    1. A compelling storyline with beginning, middle, and end
    2. 4-6 panel breakdown with detailed visual descriptions
    3. Character descriptions and dialogue for each panel
    4. Visual style guidelines and mood specifications
  expected_output: >
    A detailed comic script with panel-by-panel descriptions,
    character details, dialogue, and visual style notes
  agent: story_writer

image_generation_task:
  description: >
    Generate comic panel images based on the story script:
    1. Create consistent character designs across panels
    2. Generate each panel image using gemini/gemini-2.5-flash-preview-04-17
    3. Ensure visual continuity and comic art style
    4. Maintain consistent lighting and color palette
  expected_output: >
    A collection of comic panel images with consistent style
    and character representation
  agent: visual_director
  context:
    - story_creation_task

comic_assembly_task:
  description: >
    Assemble the final comic strip:
    1. Arrange panels in proper comic layout
    2. Add speech bubbles and dialogue
    3. Include title and credits
    4. Create final presentation format
  expected_output: >
    A complete comic strip with assembled panels, dialogue,
    and professional presentation
  agent: comic_assembler
  context:
    - story_creation_task
    - image_generation_task
  output_file: output/final_comic.md
