story_creation_task:
  description: >
    Create a comic story script for {topic} with:
    1. A compelling storyline with beginning, middle, and end
    2. 4-6 panel breakdown with detailed visual descriptions
    3. Character descriptions and dialogue for each panel
    4. Visual style guidelines and mood specifications
  expected_output: >
    A detailed comic script with panel-by-panel descriptions,
    character details, dialogue, and visual style notes
  agent: story_writer

orchestrated_generation_task:
  description: |
    Orchestrate complete comic generation with validation and retry logic.

    ORCHESTRATION WORKFLOW:
    1. INITIAL GENERATION: Delegate to Visual Director for initial panel generation
    2. VALIDATION CHECK: Review generation results and validate panel completeness
    3. RETRY LOGIC: For any failed or missing panels:
       - Identify specific failed panel numbers
       - Delegate regeneration of ONLY failed panels to Visual Director
       - Maximum 3 retry attempts per panel
       - Continue until all panels succeed or max retries reached
    4. FINAL VALIDATION: Ensure all panels are complete before proceeding

    RETRY STRATEGY:
    - Track failed panels individually
    - Regenerate only missing/failed panels (not all panels)
    - Provide clear feedback to Visual Director about what needs regeneration
    - Implement progressive retry with detailed failure analysis

    QUALITY CONTROL:
    - Work with Evaluator to validate panel existence
    - Ensure no fabricated filenames are accepted
    - Maintain detailed logs of retry attempts and results
    - Report final success/failure status with specific details

    RESOURCE MANAGEMENT:
    - Maximum retry limit: 3 attempts per panel
    - Total generation timeout: 10 minutes
    - Graceful degradation for persistent failures
    - Clear error reporting for manual intervention

    SUCCESS CRITERIA:
    - ALL panels (1-6) successfully generated with real image files
    - All images exist in both backend and frontend locations
    - Panel validation returns 100% PASS status
    - No fabricated or non-existent image references
  expected_output: >
    Complete orchestration report with:
    - Initial generation attempt results
    - Retry attempts and outcomes for failed panels
    - Final panel generation status (SUCCESS/PARTIAL/FAILED)
    - Detailed panel-by-panel validation results
    - Total attempts, successes, and failures
    - Clear recommendation for next steps (proceed to assembly or manual intervention)
  agent: orchestrator
  context:
    - story_creation_task

image_generation_task:
  description: |
    Generate comic panel images based on the story script with consistent character appearances using Option 6 approach.

    STEP 1 - CHARACTER CONSISTENCY SETUP (Option 6 Approach):
    If the story contains named characters, FIRST attempt to create character references:
    1. Identify all main characters from the story
    2. For EACH character, use the Character Consistency Tool with action "create_character":
       - character_name: The character's name
       - character_description: Detailed physical description from the story
       - existing_image_path: (optional) Path to existing character image if available
    3. If character reference creation FAILS, note the failure and continue with panel generation
    4. DO NOT stop the entire process if character reference creation fails

    STEP 2 - PANEL GENERATION (MANDATORY FOR ALL PANELS):
    You MUST generate ALL panels described in the story. For each panel:
    1. Extract the visual description for that panel
    2. Identify which named characters appear in this panel
    3. Choose the CORRECT tool based on character count:
       - SINGLE CHARACTER: Use Character Consistency Tool with action "generate_scene"
       - MULTIPLE CHARACTERS (2+): Use Multi-Character Scene Tool
       - NO NAMED CHARACTERS: Use Gemini Image Generator
       - REFINING EXISTING IMAGE: Use Image Refinement Tool
    4. For failed character references, include detailed character descriptions in prompts
    5. You MUST call the actual tool and record the REAL returned image path
    6. NEVER fabricate or make up image paths - only use paths returned by tools

    TOOL SELECTION CRITERIA:
    - CharacterConsistencyTool: Single character scenes with existing character references
    - MultiCharacterSceneTool: Scenes requiring 2+ characters using multiple character references
    - ImageRefinementTool: Modifying existing panels with specific refinement requirements
    - GeminiImageTool: Scenes with no named characters OR fallback when character tools fail

    TOOL CALL FORMATS:
    - CharacterConsistencyTool: action="generate_scene", character_name="Name", scene_description="Description", panel_number=X
    - MultiCharacterSceneTool: character_names=["Name1", "Name2"], scene_description="Description", panel_number=X
    - ImageRefinementTool: base_image_path="path/to/image.png", refinement_prompt="How to modify", panel_number=X
    - GeminiImageTool: prompt="Panel X: Description", base_image_paths=null

    IMPORTANT: All tools use the same Gemini server endpoint (generate-image) but with different parameters:
    - CharacterConsistencyTool: Uses single base_image_paths for character reference
    - MultiCharacterSceneTool: Uses multiple base_image_paths for character composition
    - ImageRefinementTool: Uses single base_image_paths with refinement prompt
    - GeminiImageTool: Uses no base images, just prompt

    ERROR HANDLING REQUIREMENTS:
    - If character reference creation fails, continue with direct image generation
    - If a panel generation fails, note it and continue with remaining panels
    - ALWAYS attempt to generate ALL panels - never stop early
    - Use fallback methods when primary methods fail
    - For failed character references, include detailed character descriptions in Gemini prompts

    FALLBACK STRATEGY FOR CHARACTER CONSISTENCY:
    When character references fail, enhance your Gemini Image Generator prompts with:
    - Detailed physical description of the character from the story
    - Consistent style notes (e.g., "same character as previous panels")
    - Visual continuity cues (clothing, facial features, build, etc.)

    TOOL CALL REQUIREMENTS:
    - You MUST actually call tools for each panel generation
    - NEVER make up fake filenames like "panel2.png", "panel3.png" etc.
    - ONLY use image paths actually returned by the tools
    - If a tool call fails, record "FAILED" for that panel
    - Continue with remaining panels even if early ones fail

    CRITICAL TOOL ARGUMENT FORMAT:
    When calling Gemini Image Generator, use EXACTLY this format:
    - prompt: "Panel X: your description text here" (simple string, NOT a dictionary, where X is the panel number)
    - base_image_paths: null (or list of paths if needed)

    INCORRECT FORMAT (causes validation errors):
    - prompt: {"description": "text", "type": "str"} ❌

    CORRECT FORMAT:
    - prompt: "Panel X: A whimsical comic panel showing..." ✅ (where X is the actual panel number)

    MANDATORY FINAL SUMMARY:
    You MUST provide a complete summary with:
    - Character references: [list with success/failure status]
    - Panel generation results for EACH panel (1 through total):
      - Panel X: [actual tool-returned path OR "FAILED" with reason]
    - Total successful generations vs total attempted
    - Specific failure reasons for any failed panels

    Ensure visual continuity and comic art style (same characters, styles, palette).
    Maintain consistent lighting and color palette.
  expected_output: >
    A complete summary with ACTUAL results only (no fabricated data):

    Character References:
    - [Character Name]: [SUCCESS: path] OR [FAILED: reason]

    Panel Generation Results:
    - Panel 1: [actual tool-returned path OR "FAILED: reason"]
    - Panel 2: [actual tool-returned path OR "FAILED: reason"] 
    - Panel 3: [actual tool-returned path OR "FAILED: reason"]
    - Panel 4: [actual tool-returned path OR "FAILED: reason"]
    - Panel 5: [actual tool-returned path OR "FAILED: reason"]
    - Panel 6: [actual tool-returned path OR "FAILED: reason"]

    CRITICAL: The final output of this task MUST be ONLY a JSON object mapping each panel number (e.g., "1", "2") to its generated image filename (e.g., "comic_panels/image_name.png").
    Example: {"1": "comic_panels/server_generated_gemini-image-tutorial_1758628204412.png", "2": "comic_panels/server_generated_gemini-image-tutorial_1758628220627.png", "3": "FAILED: Timeout"}

    Do NOT include any other text, explanations, or formatting. The output must be valid JSON that can be parsed directly.
  agent: visual_director
  context:
    - story_creation_task

panel_validation_task:
  description: |
    Validate that ALL comic panels referenced in the image generation results have
    corresponding actual image files in the filesystem before allowing comic assembly.

    IMPORTANT: You MUST extract the panel-to-filename mapping from the IMAGE GENERATION TASK output.
    The image generation task outputs a JSON object mapping panel numbers to actual filenames.
    Look for this JSON in the context and use it as your panel_map input.

    If you cannot find the JSON mapping in the context, STOP and report that the image generation task did not produce the expected JSON output. Do NOT create guessed filenames like "panel_1.png".

    VALIDATION REQUIREMENTS:
    1. Extract the actual panel-to-filename mapping from the image generation task results
    2. For EACH panel number and filename in the mapping:
       - Check if the filename exists in the backend output folder
       - Check if the filename exists in the frontend comic_panels folder
       - Verify the filename is not empty/corrupted
    3. Count total panels expected vs panels with valid images
    4. Identify any missing or invalid panel images

    VALIDATION CHECKS:
    - Panel completeness: All panels (1-6) have image references
    - File existence: All referenced images exist in filesystem, check on their filename
    - Path validation: All paths are real (not fabricated like "panel2.png")
    - Accessibility: Images are accessible for frontend display

    CRITICAL: Do NOT use guessed filenames like "panel_1.jpg". Only validate the actual filenames
    that were reported as generated by the image generation task.

    MANDATORY VALIDATION REPORT:
    You MUST provide a detailed validation report with:

    Panel Validation Results:
    - Panel 1: [✅ VALID: path] OR [❌ MISSING: reason]
    - Panel 2: [✅ VALID: path] OR [❌ MISSING: reason]
    - Panel 3: [✅ VALID: path] OR [❌ MISSING: reason]
    - Panel 4: [✅ VALID: path] OR [❌ MISSING: reason]
    - Panel 5: [✅ VALID: path] OR [❌ MISSING: reason]
    - Panel 6: [✅ VALID: path] OR [❌ MISSING: reason]

    File System Check:
    - Backend files found: [number]
    - Frontend files found: [number]
    - Missing files: [list of missing panels]

    VALIDATION STATUS: [PASS/FAIL]

    If FAIL: Stop the comic assembly process and report missing panels
    If PASS: Allow comic to proceed to assembly

    CRITICAL: Never approve comics with missing panel images!
  expected_output: >
    A comprehensive validation report showing:
    - Detailed panel-by-panel validation results using ACTUAL filenames from image generation
    - File system verification status
    - Overall PASS/FAIL determination
    - Specific missing panels if any failures
    - Clear recommendation for next steps

    CRITICAL: Report must be based on actual generated filenames, not guessed ones like "panel_1.jpg".
    Only comics with 100% panel validation (all actual generated files present) should be marked as PASS.
  agent: evaluator
  context:
    - story_creation_task
    - orchestrated_generation_task
    - image_generation_task

comic_assembly_task:
  description: |
    Use the Comic Layout Designer tool to create the final comic layout ONLY if validation passed.

    VALIDATION CHECK FIRST:
    1. Review the panel validation task results
    2. If validation status is FAIL, return an error message and stop
    3. If validation status is PASS, proceed with comic assembly

    COMIC ASSEMBLY (only if validation passed):
    1. Extract panel descriptions and dialogue from the story task
    2. Extract image paths from the image generation task  
    3. Call the Comic Layout Designer tool with these parameters
    4. Return ONLY the tool's markdown output - NO agent thoughts or reasoning

    CRITICAL: Do NOT proceed with assembly if the panel validation failed!
  expected_output: >
    If validation FAILED: Error message stating validation failure and requesting manual intervention
    If validation PASSED: Clean comic markdown layout with panels, images, and dialogue.
    NO agent thoughts, reasoning, or meta-commentary.
    ONLY the comic content itself or error message.
  agent: comic_assembler
  context:
    - story_creation_task
    - orchestrated_generation_task
    - panel_validation_task
